vegalize/config/routes.rb
Rails.application.routes.draw do
  resources :comentarios
  resources :restaurantes
  #root :to => redirect('/ideas')
  resources :ideas
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

vegalize/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

vegalize/app/models/comentario.rb
class Comentario < ApplicationRecord
  belongs_to :restaurante
end

vegalize/app/models/idea.rb
class Idea < ApplicationRecord
  mount_uploader :picture, PictureUploader
end

vegalize/app/models/restaurante.rb
class Restaurante < ApplicationRecord
  has_many :comentarios
end

vegalize/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

vegalize/app/controllers/comentarios_controller.rb
class ComentariosController < ApplicationController
  before_action :set_comentario, only: [:show, :edit, :update, :destroy]

  # GET /comentarios
  # GET /comentarios.json
  def index
    @comentarios = Comentario.all
  end

  # GET /comentarios/1
  # GET /comentarios/1.json
  def show
  end

  # GET /comentarios/new
  def new
    @comentario = Comentario.new
  end

  # GET /comentarios/1/edit
  def edit
  end

  # POST /comentarios
  # POST /comentarios.json
  def create
    @comentario = Comentario.new(comentario_params)

    respond_to do |format|
      if @comentario.save
        format.html { redirect_to @comentario, notice: 'Comentario was successfully created.' }
        format.json { render :show, status: :created, location: @comentario }
      else
        format.html { render :new }
        format.json { render json: @comentario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /comentarios/1
  # PATCH/PUT /comentarios/1.json
  def update
    respond_to do |format|
      if @comentario.update(comentario_params)
        format.html { redirect_to @comentario, notice: 'Comentario was successfully updated.' }
        format.json { render :show, status: :ok, location: @comentario }
      else
        format.html { render :edit }
        format.json { render json: @comentario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /comentarios/1
  # DELETE /comentarios/1.json
  def destroy
    @comentario.destroy
    respond_to do |format|
      format.html { redirect_to comentarios_url, notice: 'Comentario was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_comentario
      @comentario = Comentario.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def comentario_params
      params.require(:comentario).permit(:usuario, :mensagem, :restaurante_id)
    end
end

vegalize/app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
  before_action :set_idea, only: [:show, :edit, :update, :destroy]

  # GET /ideas
  # GET /ideas.json
  def index
    @ideas = Idea.all
  end

  # GET /ideas/1
  # GET /ideas/1.json
  def show
  end

  # GET /ideas/new
  def new
    @idea = Idea.new
  end

  # GET /ideas/1/edit
  def edit
  end

  # POST /ideas
  # POST /ideas.json
  def create
    @idea = Idea.new(idea_params)

    respond_to do |format|
      if @idea.save
        format.html { redirect_to @idea, notice: 'Idea was successfully created.' }
        format.json { render :show, status: :created, location: @idea }
      else
        format.html { render :new }
        format.json { render json: @idea.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ideas/1
  # PATCH/PUT /ideas/1.json
  def update
    respond_to do |format|
      if @idea.update(idea_params)
        format.html { redirect_to @idea, notice: 'Idea was successfully updated.' }
        format.json { render :show, status: :ok, location: @idea }
      else
        format.html { render :edit }
        format.json { render json: @idea.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ideas/1
  # DELETE /ideas/1.json
  def destroy
    @idea.destroy
    respond_to do |format|
      format.html { redirect_to ideas_url, notice: 'Idea was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_idea
      @idea = Idea.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def idea_params
      params.require(:idea).permit(:name, :description, :picture)
    end
end

vegalize/app/controllers/restaurantes_controller.rb
class RestaurantesController < ApplicationController
  before_action :set_restaurante, only: [:show, :edit, :update, :destroy]

  # GET /restaurantes
  # GET /restaurantes.json
  def index
    @restaurantes = Restaurante.all
  end

  # GET /restaurantes/1
  # GET /restaurantes/1.json
  def show
    @restaurante = Restaurante.find(params[:id])
    @comentario = @restaurante.comentarios.build
  end

  # GET /restaurantes/new
  def new
    @restaurante = Restaurante.new
  end

  # GET /restaurantes/1/edit
  def edit
  end

  # POST /restaurantes
  # POST /restaurantes.json
  def create
    @restaurante = Restaurante.new(restaurante_params)

    respond_to do |format|
      if @restaurante.save
        format.html { redirect_to @restaurante, notice: 'Restaurante was successfully created.' }
        format.json { render :show, status: :created, location: @restaurante }
      else
        format.html { render :new }
        format.json { render json: @restaurante.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /restaurantes/1
  # PATCH/PUT /restaurantes/1.json
  def update
    respond_to do |format|
      if @restaurante.update(restaurante_params)
        format.html { redirect_to @restaurante, notice: 'Restaurante was successfully updated.' }
        format.json { render :show, status: :ok, location: @restaurante }
      else
        format.html { render :edit }
        format.json { render json: @restaurante.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /restaurantes/1
  # DELETE /restaurantes/1.json
  def destroy
    @restaurante.destroy
    respond_to do |format|
      format.html { redirect_to restaurantes_url, notice: 'Restaurante was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_restaurante
      @restaurante = Restaurante.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def restaurante_params
      params.require(:restaurante).permit(:nome, :endereco, :pagamento, :telefone)
    end
end

vegalize/app/helpers/application_helper.rb
module ApplicationHelper
end

vegalize/app/helpers/comentarios_helper.rb
module ComentariosHelper
end

vegalize/app/helpers/ideas_helper.rb
module IdeasHelper
end

vegalize/app/helpers/restaurantes_helper.rb
module RestaurantesHelper
end

vegalize/app/views/comentarios/_form.html.erb
<%= form_for(@comentario) do |f| %>
  <% if @comentario.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(comentario.errors.count, "error") %> prohibited this comentario from being saved:</h2>

      <ul>
      <% comentario.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :usuario %>
    <%= f.text_field :usuario %>
  </div>

  <div class="field">
    <%= f.label :mensagem %>
    <%= f.text_area :mensagem %>
  </div>

  <div class="field">
    <%= f.label :restaurante_id %>
    <%= f.number_field :restaurante_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

vegalize/app/views/comentarios/edit.html.erb
<h1>Editing Comentario</h1>

<%= render 'form', comentario: @comentario %>

<%= link_to 'Show', @comentario %> |
<%= link_to 'Back', comentarios_path %>

vegalize/app/views/comentarios/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Comentarios</h1>

<table>
  <thead>
    <tr>
      <th>Usuario</th>
      <th>Mensagem</th>
      <th>Restaurante</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @comentarios.each do |comentario| %>
      <tr>
        <td><%= comentario.usuario %></td>
        <td><%= comentario.mensagem %></td>
        <td><%= comentario.restaurante_id %></td>
        <td><%= link_to 'Show', comentario %></td>
        <td><%= link_to 'Edit', edit_comentario_path(comentario) %></td>
        <td><%= link_to 'Destroy', comentario, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Comentario', new_comentario_path %>

vegalize/app/views/comentarios/new.html.erb
<h1>New Comentario</h1>

<%= render 'form', comentario: @comentario %>

<%= link_to 'Back', comentarios_path %>

vegalize/app/views/comentarios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Usuario:</strong>
  <%= @comentario.usuario %>
</p>

<p>
  <strong>Mensagem:</strong>
  <%= @comentario.mensagem %>
</p>

<p>
  <strong>Restaurante:</strong>
  <%= @comentario.restaurante_id %>
</p>

<%= link_to 'Edit', edit_comentario_path(@comentario) %> |
<%= link_to 'Back', comentarios_path %>

vegalize/app/views/ideas/_form.html.erb
<%= form_for(@idea, :html => { :multipart => true }) do |f| %>
  <% if idea.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(idea.errors.count, "error") %> prohibited this idea from being saved:</h2>

      <ul>
      <% idea.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_area :description %>
  </div>

  <div class="field">
    <%= f.label :picture %>
    <%= f.file_field :picture %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

vegalize/app/views/ideas/edit.html.erb
<h1>Editing Idea</h1>

<%= render 'form', idea: @idea %>

<%= link_to 'Show', @idea %> |
<%= link_to 'Back', ideas_path %>

vegalize/app/views/ideas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Ideas</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Description</th>
      <th>Picture</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @ideas.each do |idea| %>
      <tr>
        <td><%= idea.name %></td>
        <td><%= idea.description %></td>
        <td><%= idea.picture %></td>
        <td><%= link_to 'Show', idea %></td>
        <td><%= link_to 'Edit', edit_idea_path(idea) %></td>
        <td><%= link_to 'Destroy', idea, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Idea', new_idea_path %>

vegalize/app/views/ideas/new.html.erb
<h1>New Idea</h1>

<%= render 'form', idea: @idea %>

<%= link_to 'Back', ideas_path %>

vegalize/app/views/ideas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @idea.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @idea.description %>
</p>

<p>
  <strong>Picture:</strong>
  <%= image_tag(@idea.picture_url, :width => 600) if @idea.picture.present? %>
</p>

<%= link_to 'Edit', edit_idea_path(@idea) %> |
<%= link_to 'Back', ideas_path %>

vegalize/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Vegalize</title>
    <%= csrf_meta_tags %>
    <link rel="stylesheet" href="http://railsgirls.com/assets/bootstrap.css">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="navbar navbar-fixed-top">
      <div class="navbar-inner">
        <div class="container">
          <a class="brand" href="/">The Idea app</a>
            <ul class="nav">
              <li class="active"><a href="/ideas">Ideas</a></li>
            </ul>
        </div>
      </div>
    </div>
    <div class="container">
        <%= yield %>
    </div>
    <footer>
      <div class="container">
        Rails Girls 2012
      </div>
    </footer>
  </body>  
</html>

vegalize/app/views/restaurantes/_form.html.erb
<%= form_for(restaurante) do |f| %>
  <% if restaurante.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(restaurante.errors.count, "error") %> prohibited this restaurante from being saved:</h2>

      <ul>
      <% restaurante.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %>
    <%= f.text_field :nome %>
  </div>

  <div class="field">
    <%= f.label :endereco %>
    <%= f.text_area :endereco %>
  </div>

  <div class="field">
    <%= f.label :telefone %>
    <%= f.text_field :telefone %>
  </div>

  <div class="field">
    <%= f.label :pagamento %>
    <%= f.text_field :pagamento %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

vegalize/app/views/restaurantes/edit.html.erb
<h1>Editing Restaurante</h1>

<%= render 'form', restaurante: @restaurante %>

<%= link_to 'Show', @restaurante %> |
<%= link_to 'Back', restaurantes_path %>

vegalize/app/views/restaurantes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Restaurantes</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Endereco</th>
      <th>Telefone</th>
      <th>Pagamento</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @restaurantes.each do |restaurante| %>
      <tr>
        <td><%= restaurante.nome %></td>
        <td><%= restaurante.endereco %></td>
        <td><%= restaurante.telefone %></td>
        <td><%= restaurante.pagamento %></td>
        <td><%= link_to 'Show', restaurante %></td>
        <td><%= link_to 'Edit', edit_restaurante_path(restaurante) %></td>
        <td><%= link_to 'Destroy', restaurante, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Restaurante', new_restaurante_path %>

vegalize/app/views/restaurantes/new.html.erb
<h1>New Restaurante</h1>

<%= render 'form', restaurante: @restaurante %>

<%= link_to 'Back', restaurantes_path %>

vegalize/app/views/restaurantes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @restaurante.nome %>
</p>

<p>
  <strong>Endereco:</strong>
  <%= @restaurante.endereco %>
</p>

<p>
  <strong>Telefone:</strong>
  <%= @restaurante.telefone %>
</p>

<p>
  <strong>Pagamento:</strong>
  <%= @restaurante.pagamento %>
</p>

<h3>Comentários:</h3>
<% @restaurante.comentarios.each do |comentario| %>
  <div>
    <strong><%= comentario.usuario %></strong>
    <br />
    <p><%= comentario.mensagem %><p>
  </div>
<% end %>
<%= render 'comentarios/form' %>

<%= link_to 'Edit', edit_restaurante_path(@restaurante) %> |
<%= link_to 'Back', restaurantes_path %>